api-version: 2019-12-01
location: westus2
name: dronevideo
properties:
  containers:
  - name: streamlitapp
    properties:
      image: dronevideoregistry.azurecr.io/drone_video_analysis:v1
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      resources:
        requests:
          cpu: 2.0
          memoryInGB: 1.5
  imageRegistryCredentials:
  - server: dronevideoregistry.azurecr.io
    username: dronevideoregistry
    password: OIFJx8GzVEcJel0blKRMqBksPADNJ/j/ecVyHjrJSt+ACRDVnx0E
  restartPolicy: Never
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    type: Public
    dnsNameLabel: dronevideo
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups