name: drone_video_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - matplotlib
  - pip:
    - opencv-python-headless
    - lxml
    - tqdm
    - tensorflow
    - absl-py
    - easydict
    - pillow
    - pytesseract
    - streamlit 
    - gdown
    - pathlib
    - av
